/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function echo(a: number): number;
export function get_public_auth0_config(): number;
export function exchange_code_for_identity(a: number): number;
export function token_to_claims(a: number): number;
export function app_version(): number;
export function upload_file_chunk(a: number): number;
export function get_user(): number;
export function get_task(a: number): number;
export function get_report(a: number): number;
export function get_all_reports(): number;
export function get_file(a: number): number;
export function get_requirement(a: number): number;
export function get_requirement_group(a: number): number;
export function get_sections(a: number): number;
export function get_tasks_by_report(a: number): number;
export function get_tasks_by_report_and_requirement(a: number): number;
export function get_tasks_by_document(a: number): number;
export function get_requirement_groups_by_section(a: number): number;
export function get_child_requirement_groups(a: number): number;
export function get_requirements_by_group(a: number): number;
export function get_all_sections(): number;
export function get_all_files(): number;
export function get_all_requirements(): number;
export function get_all_requirement_groups(): number;
export function create_user(a: number): number;
export function create_report(a: number): number;
export function create_file(a: number): number;
export function update_user(a: number): number;
export function update_task(a: number): number;
export function user_exists(): number;
export function is_admin(): number;
export function admin_upload_report(a: number): number;
export function new_file(a: number): number;
export function admin_get_threads_by_report(a: number): number;
export function admin_get_threads_by_section(a: number): number;
export function admin_get_threads_by_requirement_group(a: number): number;
export function admin_get_threads_by_requirement(a: number): number;
export function set_websocket_event_callback(a: number): void;
export function hydrate(): void;
export function get_file_data(a: number): number;
export function __wbg_intounderlyingsource_free(a: number, b: number): void;
export function intounderlyingsource_pull(a: number, b: number): number;
export function intounderlyingsource_cancel(a: number): void;
export function __wbg_intounderlyingsink_free(a: number, b: number): void;
export function intounderlyingsink_write(a: number, b: number): number;
export function intounderlyingsink_close(a: number): number;
export function intounderlyingsink_abort(a: number, b: number): number;
export function __wbg_intounderlyingbytesource_free(a: number, b: number): void;
export function intounderlyingbytesource_type(a: number): number;
export function intounderlyingbytesource_autoAllocateChunkSize(a: number): number;
export function intounderlyingbytesource_start(a: number, b: number): void;
export function intounderlyingbytesource_pull(a: number, b: number): number;
export function intounderlyingbytesource_cancel(a: number): void;
export function __wbindgen_export_0(a: number, b: number): number;
export function __wbindgen_export_1(a: number, b: number, c: number, d: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function __wbindgen_export_3(a: number, b: number): void;
export function __wbindgen_export_4(a: number, b: number, c: number): void;
export function __wbindgen_export_5(a: number, b: number): void;
export function __wbindgen_export_6(a: number, b: number, c: number): void;
export function __wbindgen_export_7(a: number, b: number, c: number): void;
export function __wbindgen_export_8(a: number): void;
export function __wbindgen_export_9(a: number, b: number, c: number, d: number): void;
