/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function echo(a: number): number;
export function get_public_auth0_config(): number;
export function exchange_code_for_identity(a: number): number;
export function token_to_claims(a: number): number;
export function app_version(): number;
export function get_file_data(a: number): number;
export function upload_file_chunk(a: number): number;
export function get_user(): number;
export function get_report(a: number): number;
export function get_reports(): number;
export function create_user(a: number): number;
export function create_report(a: number): number;
export function user_exists(): number;
export function is_admin(): number;
export function hydrate(): void;
export function __wbg_intounderlyingsink_free(a: number, b: number): void;
export function intounderlyingsink_write(a: number, b: number): number;
export function intounderlyingsink_close(a: number): number;
export function intounderlyingsink_abort(a: number, b: number): number;
export function __wbg_intounderlyingbytesource_free(a: number, b: number): void;
export function intounderlyingbytesource_type(a: number): number;
export function intounderlyingbytesource_autoAllocateChunkSize(a: number): number;
export function intounderlyingbytesource_start(a: number, b: number): void;
export function intounderlyingbytesource_pull(a: number, b: number): number;
export function intounderlyingbytesource_cancel(a: number): void;
export function __wbg_intounderlyingsource_free(a: number, b: number): void;
export function intounderlyingsource_pull(a: number, b: number): number;
export function intounderlyingsource_cancel(a: number): void;
export function __wbindgen_export_0(a: number, b: number): number;
export function __wbindgen_export_1(a: number, b: number, c: number, d: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function __wbindgen_export_3(a: number, b: number, c: number): void;
export function __wbindgen_export_4(a: number, b: number, c: number): void;
export function __wbindgen_export_5(a: number): void;
export function __wbindgen_export_6(a: number, b: number, c: number, d: number): void;
